version: '3'
services:
  example:
    build: ./Domain Software/simple-website-app/
    ports:
      - "3000:3000"
  sidecarregistration:
    build: ./Platform Sidecars/spsc-app-registration/
    env_file:
      - ./Platform Sidecars/spsc-app-registration/config.env

