version: '3'
services:
  example:
    build: ./example/
    ports:
      - "3000:3000"
  sidecarregistration:
    build: ./sidecar-registration/
    env_file:
      - ./sidecar-registration/config.env

